"""
Base Strategy Class with common functionality.
"""
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, List, Dict, Any
from datetime import datetime


class SignalType(Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"


class Regime(Enum):
    TRENDING = "TRENDING"
    CHOPPY = "CHOPPY"
    MIXED = "MIXED"


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    strategy_name: str
    signal_type: SignalType
    price: float
    timestamp: datetime
    confidence: float  # 0-100
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    trailing_stop: bool = False
    trailing_stop_pct: Optional[float] = None
    reasoning: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'strategy': self.strategy_name,
            'signal': self.signal_type.value,
            'price': self.price,
            'timestamp': self.timestamp.isoformat() if isinstance(self.timestamp, datetime) else str(self.timestamp),
            'confidence': self.confidence,
            'stop_loss': self.stop_loss,
            'take_profit': self.take_profit,
            'trailing_stop': self.trailing_stop,
            'trailing_stop_pct': self.trailing_stop_pct,
            'reasoning': self.reasoning,
            'metadata': self.metadata
        }


@dataclass
class Position:
    """Active trading position."""
    strategy_name: str
    entry_price: float
    entry_time: datetime
    side: str  # 'long' or 'short'
    size: float = 1.0
    stop_loss: float = 0.0
    take_profit: float = 0.0
    trailing_stop_active: bool = False
    trailing_stop_price: float = 0.0
    highest_price: float = 0.0  # For trailing long
    lowest_price: float = float('inf')  # For trailing short
    pnl: float = 0.0
    status: str = 'open'  # 'open', 'closed', 'stopped'
    fill_ratio: float = 1.0
    initial_size: float = 0.0
    partial_exit_done: bool = False
    # Regime-aware trailing stop state
    break_even_stop_active: bool = False
    trailing_activation_pnl_met: bool = False
    partial_take_profit_price: float = 0.0
    signal_bar_index: Optional[int] = None
    entry_bar_index: Optional[int] = None
    signal_timestamp: Optional[str] = None
    signal_price: Optional[float] = None
    signal_metadata: Dict[str, Any] = field(default_factory=dict)
    
    def update_trailing_stop(self, current_price: float, trailing_pct: float):
        """Update trailing stop based on price movement."""
        if self.side == 'long':
            if current_price > self.highest_price:
                self.highest_price = current_price
                new_stop = current_price * (1 - trailing_pct / 100)
                if new_stop > self.trailing_stop_price:
                    self.trailing_stop_price = new_stop
        else:  # short
            if current_price < self.lowest_price:
                self.lowest_price = current_price
                new_stop = current_price * (1 + trailing_pct / 100)
                if new_stop < self.trailing_stop_price or self.trailing_stop_price == 0:
                    self.trailing_stop_price = new_stop
    
    def check_stop_hit(self, current_price: float) -> bool:
        """Check if stop loss or trailing stop is hit."""
        if self.trailing_stop_active and self.trailing_stop_price > 0:
            if self.side == 'long' and current_price <= self.trailing_stop_price:
                return True
            if self.side == 'short' and current_price >= self.trailing_stop_price:
                return True
        
        if self.stop_loss > 0:
            if self.side == 'long' and current_price <= self.stop_loss:
                return True
            if self.side == 'short' and current_price >= self.stop_loss:
                return True
        return False
    
    def check_take_profit_hit(self, current_price: float) -> bool:
        """Check if take profit is hit."""
        if self.take_profit > 0:
            if self.side == 'long' and current_price >= self.take_profit:
                return True
            if self.side == 'short' and current_price <= self.take_profit:
                return True
        return False
    
    def calculate_pnl(self, current_price: float) -> float:
        """Calculate current PnL."""
        if self.side == 'long':
            self.pnl = (current_price - self.entry_price) / self.entry_price * 100 * self.size
        else:
            self.pnl = (self.entry_price - current_price) / self.entry_price * 100 * self.size
        return self.pnl
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'strategy': self.strategy_name,
            'entry_price': self.entry_price,
            'entry_time': self.entry_time.isoformat() if isinstance(self.entry_time, datetime) else str(self.entry_time),
            'side': self.side,
            'size': self.size,
            'stop_loss': self.stop_loss,
            'take_profit': self.take_profit,
            'trailing_stop_active': self.trailing_stop_active,
            'trailing_stop_price': self.trailing_stop_price,
            'highest_price': self.highest_price,
            'lowest_price': self.lowest_price,
            'pnl': round(self.pnl, 2),
            'status': self.status,
            'fill_ratio': self.fill_ratio,
            'initial_size': self.initial_size if self.initial_size else self.size,
            'partial_exit_done': self.partial_exit_done,
            'partial_take_profit_price': self.partial_take_profit_price,
            'signal_bar_index': self.signal_bar_index,
            'entry_bar_index': self.entry_bar_index,
            'signal_timestamp': self.signal_timestamp,
            'signal_price': self.signal_price,
            'signal_metadata': self.signal_metadata,
            'break_even_stop_active': self.break_even_stop_active,
            'trailing_activation_pnl_met': self.trailing_activation_pnl_met,
        }


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    """
    
    def __init__(self, name: str, regimes: List[Regime]):
        self.name = name
        self.allowed_regimes = regimes
        self.positions: List[Position] = []
        self.signals_history: List[Signal] = []
        self.enabled = True
        
    @abstractmethod
    def generate_signal(
        self,
        current_price: float,
        ohlcv: Dict[str, List[float]],
        indicators: Dict[str, Any],
        regime: Regime,
        timestamp: datetime
    ) -> Optional[Signal]:
        """
        Generate trading signal based on market data.
        
        Args:
            current_price: Current market price
            ohlcv: Dict with 'open', 'high', 'low', 'close', 'volume' arrays
            indicators: Dict with indicator values (sma, ema, rsi, atr, vwap)
            regime: Current market regime
            timestamp: Current timestamp
            
        Returns:
            Signal object or None
        """
        pass
    
    def is_allowed_in_regime(self, regime: Regime) -> bool:
        """Check if strategy is allowed in current regime."""
        return regime in self.allowed_regimes
    
    def calculate_atr_stop(self, price: float, atr: float, multiplier: float = 2.0, side: str = 'long') -> float:
        """Calculate ATR-based stop loss."""
        if side == 'long':
            return price - (atr * multiplier)
        return price + (atr * multiplier)
    
    def calculate_percent_stop(self, price: float, percent: float, side: str = 'long') -> float:
        """Calculate percentage-based stop loss."""
        if side == 'long':
            return price * (1 - percent / 100)
        return price * (1 + percent / 100)
    
    def calculate_take_profit(self, entry: float, stop_loss: float, rr_ratio: float = 2.0, side: str = 'long') -> float:
        """Calculate take profit based on risk-reward ratio."""
        risk = abs(entry - stop_loss)
        if side == 'long':
            return entry + (risk * rr_ratio)
        return entry - (risk * rr_ratio)
    
    def get_vwap_distance(self, price: float, vwap: float) -> float:
        """Calculate distance from VWAP as percentage."""
        return (price - vwap) / vwap * 100
    
    def check_volume_confirmation(self, current_volume: float, avg_volume: float, threshold: float = 1.5) -> bool:
        """Check if volume confirms the move."""
        return current_volume >= avg_volume * threshold

    def get_volume_stats(self, volumes: List[float], lookback: int = 20) -> Dict[str, float]:
        """Return current, average, and ratio for volume."""
        if not volumes:
            return {"current": 0.0, "avg": 0.0, "ratio": 0.0}
        window = min(lookback, len(volumes))
        avg_volume = sum(volumes[-window:]) / window if window else 0.0
        current_volume = volumes[-1] if volumes else 0.0
        ratio = (current_volume / avg_volume) if avg_volume else 0.0
        return {"current": current_volume, "avg": avg_volume, "ratio": ratio}

    def volume_adjusted_pct(
        self,
        base_pct: float,
        volume_ratio: float,
        min_ratio: float = 0.5,
        max_ratio: float = 3.0
    ) -> float:
        """Scale percent by volume ratio (higher volume -> tighter stops)."""
        ratio = volume_ratio if volume_ratio > 0 else 1.0
        ratio = max(min(ratio, max_ratio), min_ratio)
        return base_pct / ratio
    
    def add_signal(self, signal: Signal):
        """Add signal to history."""
        self.signals_history.append(signal)
    
    def get_last_signal(self) -> Optional[Signal]:
        """Get the most recent signal."""
        return self.signals_history[-1] if self.signals_history else None
    
    def open_position(self, signal: Signal) -> Position:
        """Open a new position based on signal."""
        side = 'long' if signal.signal_type == SignalType.BUY else 'short'
        position = Position(
            strategy_name=self.name,
            entry_price=signal.price,
            entry_time=signal.timestamp,
            side=side,
            stop_loss=signal.stop_loss or 0,
            take_profit=signal.take_profit or 0,
            trailing_stop_active=signal.trailing_stop,
            highest_price=signal.price if side == 'long' else 0,
            lowest_price=signal.price if side == 'short' else float('inf')
        )
        self.positions.append(position)
        return position
    
    def get_open_positions(self) -> List[Position]:
        """Get all open positions."""
        return [p for p in self.positions if p.status == 'open']
    
    def to_dict(self) -> Dict[str, Any]:
        """Serialize strategy state."""
        return {
            'name': self.name,
            'allowed_regimes': [r.value for r in self.allowed_regimes],
            'enabled': self.enabled,
            'open_positions': len(self.get_open_positions()),
            'total_signals': len(self.signals_history),
            'last_signal': self.get_last_signal().to_dict() if self.get_last_signal() else None
        }
