"""Core TradingConfig kwargs for from_dict normalization."""

from __future__ import annotations

from typing import Any, Dict, TYPE_CHECKING

if TYPE_CHECKING:
    from ....trading_config import TradingConfig


def build_core_kwargs(
    cls: type["TradingConfig"],
    raw: Dict[str, Any],
    defaults: "TradingConfig",
    runtime_formula_fields: Dict[str, Any],
    stop_mode: str,
) -> Dict[str, Any]:
    return dict(
        regime_detection_minutes=max(
            1,
            cls._to_int(raw.get("regime_detection_minutes"), defaults.regime_detection_minutes),
        ),
        regime_refresh_bars=max(
            1,
            cls._to_int(raw.get("regime_refresh_bars"), defaults.regime_refresh_bars),
        ),
        account_size_usd=max(
            0.0,
            cls._to_float(raw.get("account_size_usd"), defaults.account_size_usd),
        ),
        risk_per_trade_pct=max(
            0.1,
            cls._to_float(raw.get("risk_per_trade_pct"), defaults.risk_per_trade_pct),
        ),
        max_position_notional_pct=max(
            1.0,
            cls._to_float(
                raw.get("max_position_notional_pct"),
                defaults.max_position_notional_pct,
            ),
        ),
        max_fill_participation_rate=min(
            1.0,
            max(
                0.01,
                cls._to_float(
                    raw.get("max_fill_participation_rate"),
                    defaults.max_fill_participation_rate,
                ),
            ),
        ),
        min_fill_ratio=min(
            1.0,
            max(
                0.01,
                cls._to_float(raw.get("min_fill_ratio"), defaults.min_fill_ratio),
            ),
        ),
        enable_partial_take_profit=cls._to_bool(
            raw.get("enable_partial_take_profit"),
            defaults.enable_partial_take_profit,
        ),
        partial_take_profit_rr=max(
            0.25,
            cls._to_float(raw.get("partial_take_profit_rr"), defaults.partial_take_profit_rr),
        ),
        partial_take_profit_fraction=min(
            0.95,
            max(
                0.05,
                cls._to_float(
                    raw.get("partial_take_profit_fraction"),
                    defaults.partial_take_profit_fraction,
                ),
            ),
        ),
        partial_flow_deterioration_min_r=max(
            0.0,
            cls._to_float(
                raw.get("partial_flow_deterioration_min_r"),
                defaults.partial_flow_deterioration_min_r,
            ),
        ),
        partial_flow_deterioration_skip_be=cls._to_bool(
            raw.get("partial_flow_deterioration_skip_be"),
            defaults.partial_flow_deterioration_skip_be,
        ),
        partial_protect_min_mfe_r=max(
            0.0,
            cls._to_float(
                raw.get("partial_protect_min_mfe_r"),
                defaults.partial_protect_min_mfe_r,
            ),
        ),
        trailing_activation_pct=max(
            0.0,
            cls._to_float(raw.get("trailing_activation_pct"), defaults.trailing_activation_pct),
        ),
        break_even_buffer_pct=max(
            0.0,
            cls._to_float(raw.get("break_even_buffer_pct"), defaults.break_even_buffer_pct),
        ),
        break_even_min_hold_bars=max(
            1,
            cls._to_int(
                raw.get("break_even_min_hold_bars"),
                defaults.break_even_min_hold_bars,
            ),
        ),
        break_even_activation_min_mfe_pct=max(
            0.0,
            cls._to_float(
                raw.get("break_even_activation_min_mfe_pct"),
                defaults.break_even_activation_min_mfe_pct,
            ),
        ),
        break_even_activation_min_r=max(
            0.0,
            cls._to_float(
                raw.get("break_even_activation_min_r"),
                defaults.break_even_activation_min_r,
            ),
        ),
        break_even_activation_min_r_trending_5m=max(
            0.0,
            cls._to_float(
                raw.get("break_even_activation_min_r_trending_5m"),
                defaults.break_even_activation_min_r_trending_5m,
            ),
        ),
        break_even_activation_min_r_choppy_5m=max(
            0.0,
            cls._to_float(
                raw.get("break_even_activation_min_r_choppy_5m"),
                defaults.break_even_activation_min_r_choppy_5m,
            ),
        ),
        break_even_activation_use_levels=cls._to_bool(
            raw.get("break_even_activation_use_levels"),
            defaults.break_even_activation_use_levels,
        ),
        break_even_activation_use_l2=cls._to_bool(
            raw.get("break_even_activation_use_l2"),
            defaults.break_even_activation_use_l2,
        ),
        break_even_level_buffer_pct=max(
            0.0,
            cls._to_float(
                raw.get("break_even_level_buffer_pct"),
                defaults.break_even_level_buffer_pct,
            ),
        ),
        break_even_level_max_distance_pct=max(
            0.01,
            cls._to_float(
                raw.get("break_even_level_max_distance_pct"),
                defaults.break_even_level_max_distance_pct,
            ),
        ),
        break_even_level_min_confluence=max(
            0,
            cls._to_int(
                raw.get("break_even_level_min_confluence"),
                defaults.break_even_level_min_confluence,
            ),
        ),
        break_even_level_min_tests=max(
            0,
            cls._to_int(
                raw.get("break_even_level_min_tests"),
                defaults.break_even_level_min_tests,
            ),
        ),
        break_even_l2_signed_aggression_min=max(
            0.0,
            cls._to_float(
                raw.get("break_even_l2_signed_aggression_min"),
                defaults.break_even_l2_signed_aggression_min,
            ),
        ),
        break_even_l2_imbalance_min=max(
            0.0,
            cls._to_float(
                raw.get("break_even_l2_imbalance_min"),
                defaults.break_even_l2_imbalance_min,
            ),
        ),
        break_even_l2_book_pressure_min=max(
            0.0,
            cls._to_float(
                raw.get("break_even_l2_book_pressure_min"),
                defaults.break_even_l2_book_pressure_min,
            ),
        ),
        break_even_l2_spread_bps_max=max(
            0.0,
            cls._to_float(
                raw.get("break_even_l2_spread_bps_max"),
                defaults.break_even_l2_spread_bps_max,
            ),
        ),
        break_even_costs_pct=max(
            0.0,
            cls._to_float(
                raw.get("break_even_costs_pct"),
                defaults.break_even_costs_pct,
            ),
        ),
        break_even_min_buffer_pct=max(
            0.0,
            cls._to_float(
                raw.get("break_even_min_buffer_pct"),
                defaults.break_even_min_buffer_pct,
            ),
        ),
        break_even_atr_buffer_k=max(
            0.0,
            cls._to_float(
                raw.get("break_even_atr_buffer_k"),
                defaults.break_even_atr_buffer_k,
            ),
        ),
        break_even_5m_atr_buffer_k=max(
            0.0,
            cls._to_float(
                raw.get("break_even_5m_atr_buffer_k"),
                defaults.break_even_5m_atr_buffer_k,
            ),
        ),
        break_even_tick_size=max(
            0.0,
            cls._to_float(
                raw.get("break_even_tick_size"),
                defaults.break_even_tick_size,
            ),
        ),
        break_even_min_tick_buffer=max(
            0,
            cls._to_int(
                raw.get("break_even_min_tick_buffer"),
                defaults.break_even_min_tick_buffer,
            ),
        ),
        break_even_anti_spike_bars=max(
            0,
            cls._to_int(
                raw.get("break_even_anti_spike_bars"),
                defaults.break_even_anti_spike_bars,
            ),
        ),
        break_even_anti_spike_hits_required=max(
            1,
            cls._to_int(
                raw.get("break_even_anti_spike_hits_required"),
                defaults.break_even_anti_spike_hits_required,
            ),
        ),
        break_even_anti_spike_require_close_beyond=cls._to_bool(
            raw.get("break_even_anti_spike_require_close_beyond"),
            defaults.break_even_anti_spike_require_close_beyond,
        ),
        break_even_5m_no_go_proximity_pct=max(
            0.0,
            cls._to_float(
                raw.get("break_even_5m_no_go_proximity_pct"),
                defaults.break_even_5m_no_go_proximity_pct,
            ),
        ),
        break_even_5m_mfe_atr_factor=max(
            0.0,
            cls._to_float(
                raw.get("break_even_5m_mfe_atr_factor"),
                defaults.break_even_5m_mfe_atr_factor,
            ),
        ),
        break_even_5m_l2_bias_threshold=max(
            0.0,
            cls._to_float(
                raw.get("break_even_5m_l2_bias_threshold"),
                defaults.break_even_5m_l2_bias_threshold,
            ),
        ),
        break_even_5m_l2_bias_tighten_factor=max(
            0.1,
            min(
                2.0,
                cls._to_float(
                    raw.get("break_even_5m_l2_bias_tighten_factor"),
                    defaults.break_even_5m_l2_bias_tighten_factor,
                ),
            ),
        ),
        break_even_movement_formula_enabled=cls._to_bool(
            runtime_formula_fields.get(
                "break_even_movement_formula_enabled",
                raw.get("break_even_movement_formula_enabled"),
            ),
            defaults.break_even_movement_formula_enabled,
        ),
        break_even_movement_formula=cls._to_text(
            runtime_formula_fields.get(
                "break_even_movement_formula",
                raw.get("break_even_movement_formula"),
            ),
            defaults.break_even_movement_formula,
        ),
        break_even_proof_formula_enabled=cls._to_bool(
            runtime_formula_fields.get(
                "break_even_proof_formula_enabled",
                raw.get("break_even_proof_formula_enabled"),
            ),
            defaults.break_even_proof_formula_enabled,
        ),
        break_even_proof_formula=cls._to_text(
            runtime_formula_fields.get(
                "break_even_proof_formula",
                raw.get("break_even_proof_formula"),
            ),
            defaults.break_even_proof_formula,
        ),
        break_even_activation_formula_enabled=cls._to_bool(
            runtime_formula_fields.get(
                "break_even_activation_formula_enabled",
                raw.get("break_even_activation_formula_enabled"),
            ),
            defaults.break_even_activation_formula_enabled,
        ),
        break_even_activation_formula=cls._to_text(
            runtime_formula_fields.get(
                "break_even_activation_formula",
                raw.get("break_even_activation_formula"),
            ),
            defaults.break_even_activation_formula,
        ),
        break_even_trailing_handoff_formula_enabled=cls._to_bool(
            runtime_formula_fields.get(
                "break_even_trailing_handoff_formula_enabled",
                raw.get("break_even_trailing_handoff_formula_enabled"),
            ),
            defaults.break_even_trailing_handoff_formula_enabled,
        ),
        break_even_trailing_handoff_formula=cls._to_text(
            runtime_formula_fields.get(
                "break_even_trailing_handoff_formula",
                raw.get("break_even_trailing_handoff_formula"),
            ),
            defaults.break_even_trailing_handoff_formula,
        ),
        trailing_enabled_in_choppy=cls._to_bool(
            raw.get("trailing_enabled_in_choppy"),
            defaults.trailing_enabled_in_choppy,
        ),
        time_exit_bars=max(
            1,
            cls._to_int(raw.get("time_exit_bars"), defaults.time_exit_bars),
        ),
        time_exit_formula_enabled=cls._to_bool(
            runtime_formula_fields.get(
                "time_exit_formula_enabled",
                raw.get("time_exit_formula_enabled"),
            ),
            defaults.time_exit_formula_enabled,
        ),
        time_exit_formula=cls._to_text(
            runtime_formula_fields.get(
                "time_exit_formula",
                raw.get("time_exit_formula"),
            ),
            defaults.time_exit_formula,
        ),
        adverse_flow_exit_enabled=cls._to_bool(
            raw.get("adverse_flow_exit_enabled"),
            defaults.adverse_flow_exit_enabled,
        ),
        adverse_flow_threshold=max(
            0.02,
            cls._to_float(raw.get("adverse_flow_threshold"), defaults.adverse_flow_threshold),
        ),
        adverse_flow_min_hold_bars=max(
            1,
            cls._to_int(raw.get("adverse_flow_min_hold_bars"), defaults.adverse_flow_min_hold_bars),
        ),
        adverse_flow_consistency_threshold=max(
            0.02,
            cls._to_float(
                raw.get("adverse_flow_consistency_threshold"),
                defaults.adverse_flow_consistency_threshold,
            ),
        ),
        adverse_book_pressure_threshold=max(
            0.02,
            cls._to_float(
                raw.get("adverse_book_pressure_threshold"),
                defaults.adverse_book_pressure_threshold,
            ),
        ),
        adverse_flow_exit_formula_enabled=cls._to_bool(
            runtime_formula_fields.get(
                "adverse_flow_exit_formula_enabled",
                raw.get("adverse_flow_exit_formula_enabled"),
            ),
            defaults.adverse_flow_exit_formula_enabled,
        ),
        adverse_flow_exit_formula=cls._to_text(
            runtime_formula_fields.get(
                "adverse_flow_exit_formula",
                raw.get("adverse_flow_exit_formula"),
            ),
            defaults.adverse_flow_exit_formula,
        ),
        stop_loss_mode=stop_mode,
        fixed_stop_loss_pct=max(
            0.0,
            cls._to_float(raw.get("fixed_stop_loss_pct"), defaults.fixed_stop_loss_pct),
        ),
        l2_confirm_enabled=cls._to_bool(raw.get("l2_confirm_enabled"), defaults.l2_confirm_enabled),
        l2_min_delta=cls._to_float(raw.get("l2_min_delta"), defaults.l2_min_delta),
        l2_min_imbalance=cls._to_float(raw.get("l2_min_imbalance"), defaults.l2_min_imbalance),
        l2_min_iceberg_bias=cls._to_float(raw.get("l2_min_iceberg_bias"), defaults.l2_min_iceberg_bias),
        l2_lookback_bars=max(
            1,
            cls._to_int(raw.get("l2_lookback_bars"), defaults.l2_lookback_bars),
        ),
        l2_min_participation_ratio=cls._to_float(
            raw.get("l2_min_participation_ratio"),
            defaults.l2_min_participation_ratio,
        ),
        l2_min_directional_consistency=cls._to_float(
            raw.get("l2_min_directional_consistency"),
            defaults.l2_min_directional_consistency,
        ),
        l2_min_signed_aggression=cls._to_float(
            raw.get("l2_min_signed_aggression"),
            defaults.l2_min_signed_aggression,
        ),
        tcbbo_gate_enabled=cls._to_bool(
            raw.get("tcbbo_gate_enabled"), defaults.tcbbo_gate_enabled
        ),
        tcbbo_min_net_premium=cls._to_float(
            raw.get("tcbbo_min_net_premium"), defaults.tcbbo_min_net_premium
        ),
        tcbbo_sweep_boost=max(
            0.0,
            min(20.0, cls._to_float(raw.get("tcbbo_sweep_boost"), defaults.tcbbo_sweep_boost)),
        ),
        tcbbo_lookback_bars=max(
            1, cls._to_int(raw.get("tcbbo_lookback_bars"), defaults.tcbbo_lookback_bars)
        ),
    )
