"""Intraday-level TradingConfig kwargs for from_dict normalization."""

from __future__ import annotations

from typing import Any, Dict, TYPE_CHECKING

if TYPE_CHECKING:
    from ....trading_config import TradingConfig


def build_intraday_level_kwargs(
    cls: type["TradingConfig"],
    raw: Dict[str, Any],
    defaults: "TradingConfig",
) -> Dict[str, Any]:
    return dict(
        intraday_levels_enabled=cls._to_bool(
            raw.get("intraday_levels_enabled"), defaults.intraday_levels_enabled
        ),
        intraday_levels_swing_left_bars=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_swing_left_bars"),
                defaults.intraday_levels_swing_left_bars,
            ),
        ),
        intraday_levels_swing_right_bars=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_swing_right_bars"),
                defaults.intraday_levels_swing_right_bars,
            ),
        ),
        intraday_levels_test_tolerance_pct=max(
            0.0,
            cls._to_float(
                raw.get("intraday_levels_test_tolerance_pct"),
                defaults.intraday_levels_test_tolerance_pct,
            ),
        ),
        intraday_levels_break_tolerance_pct=max(
            0.0,
            cls._to_float(
                raw.get("intraday_levels_break_tolerance_pct"),
                defaults.intraday_levels_break_tolerance_pct,
            ),
        ),
        intraday_levels_breakout_volume_lookback=max(
            2,
            cls._to_int(
                raw.get("intraday_levels_breakout_volume_lookback"),
                defaults.intraday_levels_breakout_volume_lookback,
            ),
        ),
        intraday_levels_breakout_volume_multiplier=max(
            1.0,
            cls._to_float(
                raw.get("intraday_levels_breakout_volume_multiplier"),
                defaults.intraday_levels_breakout_volume_multiplier,
            ),
        ),
        intraday_levels_volume_profile_bin_size_pct=max(
            0.01,
            cls._to_float(
                raw.get("intraday_levels_volume_profile_bin_size_pct"),
                defaults.intraday_levels_volume_profile_bin_size_pct,
            ),
        ),
        intraday_levels_value_area_pct=min(
            0.95,
            max(
                0.5,
                cls._to_float(
                    raw.get("intraday_levels_value_area_pct"),
                    defaults.intraday_levels_value_area_pct,
                ),
            ),
        ),
        intraday_levels_entry_quality_enabled=cls._to_bool(
            raw.get("intraday_levels_entry_quality_enabled"),
            defaults.intraday_levels_entry_quality_enabled,
        ),
        intraday_levels_min_levels_for_context=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_min_levels_for_context"),
                defaults.intraday_levels_min_levels_for_context,
            ),
        ),
        intraday_levels_entry_tolerance_pct=max(
            0.01,
            cls._to_float(
                raw.get("intraday_levels_entry_tolerance_pct"),
                defaults.intraday_levels_entry_tolerance_pct,
            ),
        ),
        intraday_levels_break_cooldown_bars=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_break_cooldown_bars"),
                defaults.intraday_levels_break_cooldown_bars,
            ),
        ),
        intraday_levels_rotation_max_tests=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_rotation_max_tests"),
                defaults.intraday_levels_rotation_max_tests,
            ),
        ),
        intraday_levels_rotation_volume_max_ratio=min(
            2.0,
            max(
                0.1,
                cls._to_float(
                    raw.get("intraday_levels_rotation_volume_max_ratio"),
                    defaults.intraday_levels_rotation_volume_max_ratio,
                ),
            ),
        ),
        intraday_levels_recent_bounce_lookback_bars=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_recent_bounce_lookback_bars"),
                defaults.intraday_levels_recent_bounce_lookback_bars,
            ),
        ),
        intraday_levels_require_recent_bounce_for_mean_reversion=cls._to_bool(
            raw.get("intraday_levels_require_recent_bounce_for_mean_reversion"),
            defaults.intraday_levels_require_recent_bounce_for_mean_reversion,
        ),
        intraday_levels_momentum_break_max_age_bars=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_momentum_break_max_age_bars"),
                defaults.intraday_levels_momentum_break_max_age_bars,
            ),
        ),
        intraday_levels_momentum_min_room_pct=max(
            0.01,
            cls._to_float(
                raw.get("intraday_levels_momentum_min_room_pct"),
                defaults.intraday_levels_momentum_min_room_pct,
            ),
        ),
        intraday_levels_momentum_min_broken_ratio=min(
            1.0,
            max(
                0.0,
                cls._to_float(
                    raw.get("intraday_levels_momentum_min_broken_ratio"),
                    defaults.intraday_levels_momentum_min_broken_ratio,
                ),
            ),
        ),
        intraday_levels_min_confluence_score=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_min_confluence_score"),
                defaults.intraday_levels_min_confluence_score,
            ),
        ),
        intraday_levels_memory_enabled=cls._to_bool(
            raw.get("intraday_levels_memory_enabled"),
            defaults.intraday_levels_memory_enabled,
        ),
        intraday_levels_memory_min_tests=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_memory_min_tests"),
                defaults.intraday_levels_memory_min_tests,
            ),
        ),
        intraday_levels_memory_max_age_days=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_memory_max_age_days"),
                defaults.intraday_levels_memory_max_age_days,
            ),
        ),
        intraday_levels_memory_decay_after_days=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_memory_decay_after_days"),
                defaults.intraday_levels_memory_decay_after_days,
            ),
        ),
        intraday_levels_memory_decay_weight=min(
            1.0,
            max(
                0.1,
                cls._to_float(
                    raw.get("intraday_levels_memory_decay_weight"),
                    defaults.intraday_levels_memory_decay_weight,
                ),
            ),
        ),
        intraday_levels_memory_max_levels=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_memory_max_levels"),
                defaults.intraday_levels_memory_max_levels,
            ),
        ),
        intraday_levels_opening_range_enabled=cls._to_bool(
            raw.get("intraday_levels_opening_range_enabled"),
            defaults.intraday_levels_opening_range_enabled,
        ),
        intraday_levels_opening_range_minutes=max(
            5,
            cls._to_int(
                raw.get("intraday_levels_opening_range_minutes"),
                defaults.intraday_levels_opening_range_minutes,
            ),
        ),
        intraday_levels_opening_range_break_tolerance_pct=max(
            0.01,
            cls._to_float(
                raw.get("intraday_levels_opening_range_break_tolerance_pct"),
                defaults.intraday_levels_opening_range_break_tolerance_pct,
            ),
        ),
        intraday_levels_poc_migration_enabled=cls._to_bool(
            raw.get("intraday_levels_poc_migration_enabled"),
            defaults.intraday_levels_poc_migration_enabled,
        ),
        intraday_levels_poc_migration_interval_bars=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_poc_migration_interval_bars"),
                defaults.intraday_levels_poc_migration_interval_bars,
            ),
        ),
        intraday_levels_poc_migration_trend_threshold_pct=max(
            0.01,
            cls._to_float(
                raw.get("intraday_levels_poc_migration_trend_threshold_pct"),
                defaults.intraday_levels_poc_migration_trend_threshold_pct,
            ),
        ),
        intraday_levels_poc_migration_range_threshold_pct=max(
            0.01,
            cls._to_float(
                raw.get("intraday_levels_poc_migration_range_threshold_pct"),
                defaults.intraday_levels_poc_migration_range_threshold_pct,
            ),
        ),
        intraday_levels_composite_profile_enabled=cls._to_bool(
            raw.get("intraday_levels_composite_profile_enabled"),
            defaults.intraday_levels_composite_profile_enabled,
        ),
        intraday_levels_composite_profile_days=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_composite_profile_days"),
                defaults.intraday_levels_composite_profile_days,
            ),
        ),
        intraday_levels_composite_profile_current_day_weight=max(
            0.1,
            cls._to_float(
                raw.get("intraday_levels_composite_profile_current_day_weight"),
                defaults.intraday_levels_composite_profile_current_day_weight,
            ),
        ),
        intraday_levels_spike_detection_enabled=cls._to_bool(
            raw.get("intraday_levels_spike_detection_enabled"),
            defaults.intraday_levels_spike_detection_enabled,
        ),
        intraday_levels_spike_min_wick_ratio=min(
            0.95,
            max(
                0.4,
                cls._to_float(
                    raw.get("intraday_levels_spike_min_wick_ratio"),
                    defaults.intraday_levels_spike_min_wick_ratio,
                ),
            ),
        ),
        intraday_levels_prior_day_anchors_enabled=cls._to_bool(
            raw.get("intraday_levels_prior_day_anchors_enabled"),
            defaults.intraday_levels_prior_day_anchors_enabled,
        ),
        intraday_levels_gap_analysis_enabled=cls._to_bool(
            raw.get("intraday_levels_gap_analysis_enabled"),
            defaults.intraday_levels_gap_analysis_enabled,
        ),
        intraday_levels_gap_min_pct=max(
            0.0,
            cls._to_float(
                raw.get("intraday_levels_gap_min_pct"),
                defaults.intraday_levels_gap_min_pct,
            ),
        ),
        intraday_levels_gap_momentum_threshold_pct=max(
            0.1,
            cls._to_float(
                raw.get("intraday_levels_gap_momentum_threshold_pct"),
                defaults.intraday_levels_gap_momentum_threshold_pct,
            ),
        ),
        intraday_levels_rvol_filter_enabled=cls._to_bool(
            raw.get("intraday_levels_rvol_filter_enabled"),
            defaults.intraday_levels_rvol_filter_enabled,
        ),
        intraday_levels_rvol_lookback_bars=max(
            5,
            cls._to_int(
                raw.get("intraday_levels_rvol_lookback_bars"),
                defaults.intraday_levels_rvol_lookback_bars,
            ),
        ),
        intraday_levels_rvol_min_threshold=max(
            0.0,
            cls._to_float(
                raw.get("intraday_levels_rvol_min_threshold"),
                defaults.intraday_levels_rvol_min_threshold,
            ),
        ),
        intraday_levels_pullback_rvol_min_threshold=max(
            0.0,
            cls._to_float(
                raw.get("intraday_levels_pullback_rvol_min_threshold"),
                defaults.intraday_levels_pullback_rvol_min_threshold,
            ),
        ),
        intraday_levels_rvol_strong_threshold=max(
            0.1,
            cls._to_float(
                raw.get("intraday_levels_rvol_strong_threshold"),
                defaults.intraday_levels_rvol_strong_threshold,
            ),
        ),
        intraday_levels_adaptive_window_enabled=cls._to_bool(
            raw.get("intraday_levels_adaptive_window_enabled"),
            defaults.intraday_levels_adaptive_window_enabled,
        ),
        intraday_levels_adaptive_window_min_bars=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_adaptive_window_min_bars"),
                defaults.intraday_levels_adaptive_window_min_bars,
            ),
        ),
        intraday_levels_adaptive_window_rvol_threshold=max(
            0.0,
            cls._to_float(
                raw.get("intraday_levels_adaptive_window_rvol_threshold"),
                defaults.intraday_levels_adaptive_window_rvol_threshold,
            ),
        ),
        intraday_levels_adaptive_window_atr_ratio_max=max(
            0.1,
            cls._to_float(
                raw.get("intraday_levels_adaptive_window_atr_ratio_max"),
                defaults.intraday_levels_adaptive_window_atr_ratio_max,
            ),
        ),
        intraday_levels_micro_confirmation_enabled=cls._to_bool(
            raw.get("intraday_levels_micro_confirmation_enabled"),
            defaults.intraday_levels_micro_confirmation_enabled,
        ),
        intraday_levels_micro_confirmation_bars=max(
            1,
            cls._to_int(
                raw.get("intraday_levels_micro_confirmation_bars"),
                defaults.intraday_levels_micro_confirmation_bars,
            ),
        ),
        intraday_levels_micro_confirmation_disable_for_sweep=cls._to_bool(
            raw.get("intraday_levels_micro_confirmation_disable_for_sweep"),
            defaults.intraday_levels_micro_confirmation_disable_for_sweep,
        ),
        intraday_levels_micro_confirmation_sweep_bars=max(
            0,
            cls._to_int(
                raw.get("intraday_levels_micro_confirmation_sweep_bars"),
                defaults.intraday_levels_micro_confirmation_sweep_bars,
            ),
        ),
        intraday_levels_micro_confirmation_require_intrabar=cls._to_bool(
            raw.get("intraday_levels_micro_confirmation_require_intrabar"),
            defaults.intraday_levels_micro_confirmation_require_intrabar,
        ),
        intraday_levels_micro_confirmation_intrabar_window_seconds=max(
            1,
            min(
                60,
                cls._to_int(
                    raw.get("intraday_levels_micro_confirmation_intrabar_window_seconds"),
                    defaults.intraday_levels_micro_confirmation_intrabar_window_seconds,
                ),
            ),
        ),
        intraday_levels_micro_confirmation_intrabar_min_coverage_points=max(
            0,
            cls._to_int(
                raw.get("intraday_levels_micro_confirmation_intrabar_min_coverage_points"),
                defaults.intraday_levels_micro_confirmation_intrabar_min_coverage_points,
            ),
        ),
        intraday_levels_micro_confirmation_intrabar_min_move_pct=max(
            0.0,
            cls._to_float(
                raw.get("intraday_levels_micro_confirmation_intrabar_min_move_pct"),
                defaults.intraday_levels_micro_confirmation_intrabar_min_move_pct,
            ),
        ),
        intraday_levels_micro_confirmation_intrabar_min_push_ratio=min(
            1.0,
            max(
                0.0,
                cls._to_float(
                    raw.get("intraday_levels_micro_confirmation_intrabar_min_push_ratio"),
                    defaults.intraday_levels_micro_confirmation_intrabar_min_push_ratio,
                ),
            ),
        ),
        intraday_levels_micro_confirmation_intrabar_max_spread_bps=max(
            0.0,
            cls._to_float(
                raw.get("intraday_levels_micro_confirmation_intrabar_max_spread_bps"),
                defaults.intraday_levels_micro_confirmation_intrabar_max_spread_bps,
            ),
        ),
        intrabar_eval_step_seconds=max(
            1,
            min(
                60,
                cls._to_int(
                    raw.get("intrabar_eval_step_seconds"),
                    defaults.intrabar_eval_step_seconds,
                ),
            ),
        ),
        intraday_levels_confluence_sizing_enabled=cls._to_bool(
            raw.get("intraday_levels_confluence_sizing_enabled"),
            defaults.intraday_levels_confluence_sizing_enabled,
        ),
    )
