"""Tail TradingConfig kwargs for from_dict normalization."""

from __future__ import annotations

import copy
from typing import Any, Dict, TYPE_CHECKING

if TYPE_CHECKING:
    from ....trading_config import TradingConfig


def build_tail_kwargs(
    cls: type["TradingConfig"],
    raw: Dict[str, Any],
    defaults: "TradingConfig",
    *,
    selection_mode: str,
    momentum: Dict[str, Any],
    micro_mode: str,
) -> Dict[str, Any]:
    return dict(
        liquidity_sweep_detection_enabled=cls._to_bool(
            raw.get("liquidity_sweep_detection_enabled"),
            defaults.liquidity_sweep_detection_enabled,
        ),
        sweep_min_aggression_z=cls._to_float(
            raw.get("sweep_min_aggression_z"),
            defaults.sweep_min_aggression_z,
        ),
        sweep_min_book_pressure_z=cls._to_float(
            raw.get("sweep_min_book_pressure_z"),
            defaults.sweep_min_book_pressure_z,
        ),
        sweep_max_price_change_pct=max(
            0.0,
            cls._to_float(
                raw.get("sweep_max_price_change_pct"),
                defaults.sweep_max_price_change_pct,
            ),
        ),
        sweep_atr_buffer_multiplier=max(
            0.0,
            cls._to_float(
                raw.get("sweep_atr_buffer_multiplier"),
                defaults.sweep_atr_buffer_multiplier,
            ),
        ),
        context_aware_risk_enabled=cls._to_bool(
            raw.get("context_aware_risk_enabled"),
            defaults.context_aware_risk_enabled,
        ),
        context_risk_sl_buffer_pct=max(
            0.0,
            cls._to_float(
                raw.get("context_risk_sl_buffer_pct"),
                defaults.context_risk_sl_buffer_pct,
            ),
        ),
        context_risk_min_sl_pct=max(
            0.0,
            cls._to_float(
                raw.get("context_risk_min_sl_pct"),
                defaults.context_risk_min_sl_pct,
            ),
        ),
        context_risk_min_room_pct=max(
            0.0,
            cls._to_float(
                raw.get("context_risk_min_room_pct"),
                defaults.context_risk_min_room_pct,
            ),
        ),
        context_risk_min_effective_rr=max(
            0.0,
            cls._to_float(
                raw.get("context_risk_min_effective_rr"),
                defaults.context_risk_min_effective_rr,
            ),
        ),
        context_risk_trailing_tighten_zone=min(
            1.0,
            max(
                0.0,
                cls._to_float(
                    raw.get("context_risk_trailing_tighten_zone"),
                    defaults.context_risk_trailing_tighten_zone,
                ),
            ),
        ),
        context_risk_trailing_tighten_factor=min(
            1.0,
            max(
                0.0,
                cls._to_float(
                    raw.get("context_risk_trailing_tighten_factor"),
                    defaults.context_risk_trailing_tighten_factor,
                ),
            ),
        ),
        context_risk_level_trail_enabled=cls._to_bool(
            raw.get("context_risk_level_trail_enabled"),
            defaults.context_risk_level_trail_enabled,
        ),
        context_risk_max_anchor_search_pct=max(
            0.1,
            cls._to_float(
                raw.get("context_risk_max_anchor_search_pct"),
                defaults.context_risk_max_anchor_search_pct,
            ),
        ),
        context_risk_min_level_tests_for_sl=max(
            0,
            cls._to_int(
                raw.get("context_risk_min_level_tests_for_sl"),
                defaults.context_risk_min_level_tests_for_sl,
            ),
        ),
        l2_gate_mode=str(raw.get("l2_gate_mode", defaults.l2_gate_mode) or defaults.l2_gate_mode).strip().lower(),
        l2_gate_threshold=max(
            0.0,
            min(1.0, cls._to_float(raw.get("l2_gate_threshold"), defaults.l2_gate_threshold)),
        ),
        cold_start_each_day=cls._to_bool(raw.get("cold_start_each_day"), defaults.cold_start_each_day),
        premarket_trading_enabled=cls._to_bool(raw.get("premarket_trading_enabled"), defaults.premarket_trading_enabled),
        strategy_selection_mode=selection_mode,
        max_active_strategies=max(
            1,
            min(
                20,
                cls._to_int(raw.get("max_active_strategies"), defaults.max_active_strategies),
            ),
        ),
        momentum_diversification=copy.deepcopy(momentum),
        regime_filter=cls._parse_regime_filter(raw.get("regime_filter")),
        micro_confirmation_mode=micro_mode,
        micro_confirmation_volume_delta_min_pct=min(
            1.0,
            max(
                0.0,
                cls._to_float(
                    raw.get("micro_confirmation_volume_delta_min_pct"),
                    defaults.micro_confirmation_volume_delta_min_pct,
                ),
            ),
        ),
        weak_l2_fast_break_even_enabled=cls._to_bool(
            raw.get("weak_l2_fast_break_even_enabled"),
            defaults.weak_l2_fast_break_even_enabled,
        ),
        weak_l2_aggression_threshold=max(
            0.0,
            cls._to_float(
                raw.get("weak_l2_aggression_threshold"),
                defaults.weak_l2_aggression_threshold,
            ),
        ),
        weak_l2_break_even_min_hold_bars=max(
            1,
            cls._to_int(
                raw.get("weak_l2_break_even_min_hold_bars"),
                defaults.weak_l2_break_even_min_hold_bars,
            ),
        ),
        ev_relaxation_enabled=cls._to_bool(
            raw.get("ev_relaxation_enabled"),
            defaults.ev_relaxation_enabled,
        ),
        ev_relaxation_threshold=max(
            0.0,
            cls._to_float(
                raw.get("ev_relaxation_threshold"),
                defaults.ev_relaxation_threshold,
            ),
        ),
        ev_relaxation_factor=min(
            1.0,
            max(
                0.01,
                cls._to_float(
                    raw.get("ev_relaxation_factor"),
                    defaults.ev_relaxation_factor,
                ),
            ),
        ),
        intraday_levels_bounce_conflict_buffer_bars=max(
            0,
            cls._to_int(
                raw.get("intraday_levels_bounce_conflict_buffer_bars"),
                defaults.intraday_levels_bounce_conflict_buffer_bars,
            ),
        ),
        golden_setups_enabled=cls._to_bool(
            raw.get("golden_setups_enabled"),
            defaults.golden_setups_enabled,
        ),
        golden_setups_max_entries_per_day=max(
            0,
            cls._to_int(
                raw.get("golden_setups_max_entries_per_day"),
                defaults.golden_setups_max_entries_per_day,
            ),
        ),
        golden_setups_cooldown_bars=max(
            0,
            cls._to_int(
                raw.get("golden_setups_cooldown_bars"),
                defaults.golden_setups_cooldown_bars,
            ),
        ),
        golden_setups_min_l2_score=min(
            100.0,
            max(
                0.0,
                cls._to_float(
                    raw.get("golden_setups_min_l2_score"),
                    defaults.golden_setups_min_l2_score,
                ),
            ),
        ),
        golden_setup_absorption_reversal_enabled=cls._to_bool(
            raw.get("golden_setup_absorption_reversal_enabled"),
            defaults.golden_setup_absorption_reversal_enabled,
        ),
        golden_setup_ar_threshold_reduction=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_ar_threshold_reduction"),
                defaults.golden_setup_ar_threshold_reduction,
            ),
        ),
        golden_setup_ar_confidence_boost=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_ar_confidence_boost"),
                defaults.golden_setup_ar_confidence_boost,
            ),
        ),
        golden_setup_ar_tcbbo_boost=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_ar_tcbbo_boost"),
                defaults.golden_setup_ar_tcbbo_boost,
            ),
        ),
        golden_setup_gamma_squeeze_enabled=cls._to_bool(
            raw.get("golden_setup_gamma_squeeze_enabled"),
            defaults.golden_setup_gamma_squeeze_enabled,
        ),
        golden_setup_gsb_threshold_reduction=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_gsb_threshold_reduction"),
                defaults.golden_setup_gsb_threshold_reduction,
            ),
        ),
        golden_setup_gsb_confidence_boost=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_gsb_confidence_boost"),
                defaults.golden_setup_gsb_confidence_boost,
            ),
        ),
        golden_setup_gsb_tcbbo_boost=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_gsb_tcbbo_boost"),
                defaults.golden_setup_gsb_tcbbo_boost,
            ),
        ),
        golden_setup_liquidity_trap_enabled=cls._to_bool(
            raw.get("golden_setup_liquidity_trap_enabled"),
            defaults.golden_setup_liquidity_trap_enabled,
        ),
        golden_setup_lt_threshold_reduction=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_lt_threshold_reduction"),
                defaults.golden_setup_lt_threshold_reduction,
            ),
        ),
        golden_setup_lt_confidence_boost=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_lt_confidence_boost"),
                defaults.golden_setup_lt_confidence_boost,
            ),
        ),
        golden_setup_lt_tcbbo_boost=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_lt_tcbbo_boost"),
                defaults.golden_setup_lt_tcbbo_boost,
            ),
        ),
        golden_setup_iceberg_defense_enabled=cls._to_bool(
            raw.get("golden_setup_iceberg_defense_enabled"),
            defaults.golden_setup_iceberg_defense_enabled,
        ),
        golden_setup_id_threshold_reduction=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_id_threshold_reduction"),
                defaults.golden_setup_id_threshold_reduction,
            ),
        ),
        golden_setup_id_confidence_boost=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_id_confidence_boost"),
                defaults.golden_setup_id_confidence_boost,
            ),
        ),
        golden_setup_id_tcbbo_boost=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_id_tcbbo_boost"),
                defaults.golden_setup_id_tcbbo_boost,
            ),
        ),
        golden_setup_fuel_injection_enabled=cls._to_bool(
            raw.get("golden_setup_fuel_injection_enabled"),
            defaults.golden_setup_fuel_injection_enabled,
        ),
        golden_setup_fi_threshold_reduction=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_fi_threshold_reduction"),
                defaults.golden_setup_fi_threshold_reduction,
            ),
        ),
        golden_setup_fi_confidence_boost=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_fi_confidence_boost"),
                defaults.golden_setup_fi_confidence_boost,
            ),
        ),
        golden_setup_fi_tcbbo_boost=max(
            0.0,
            cls._to_float(
                raw.get("golden_setup_fi_tcbbo_boost"),
                defaults.golden_setup_fi_tcbbo_boost,
            ),
        ),
        orchestrator_strategy_weight=min(
            1.0,
            max(
                0.0,
                cls._to_float(
                    raw.get("orchestrator_strategy_weight"),
                    defaults.orchestrator_strategy_weight,
                ),
            ),
        ),
        orchestrator_strategy_only_threshold=max(
            0.0,
            cls._to_float(
                raw.get("orchestrator_strategy_only_threshold"),
                defaults.orchestrator_strategy_only_threshold,
            ),
        ),
    )
